version: '3'
services:
  leasing-api:
    container_name: leasing-api
    image: leasing-image:latest
    command: "sh -c sleep 30 && start leasing-api"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
     lease-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8080/actuator/health || exit 1" ]
      interval: 10s
      timeout: 30s
      retries: 3
  lease-db:
    container_name: lease-db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lease
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 30s
      retries: 3