version: '3'
services:
  leasing-api:
    container_name: leasing-api
    image: leasing-image:latest
#    networks:
#      - leasing-api-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      lease-db:
        condition: service_completed_successfully
  lease-db:
    container_name: lease-db
    image: mysql:latest
#    networks:
#      - leasing-api-network
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: lease
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql-data:/var/lib/mysql
#networks:
#  leasing-api-network: